export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE';

export const LOAD_PROFILE_REQUEST = 'LOAD_USER_PROFILE_REQUEST';
export const LOAD_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAILURE = 'LOAD_USER_PROFILE_FAILURE';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_USER_PROFILE_FAILURE';

export const DELETE_PROFILE_REQUEST = 'DELETE_USER_PROFILE_REQUEST';
export const DELETE_PROFILE_SUCCESS = 'DELETE_USER_PROFILE_SUCCESS';
export const DELETE_PROFILE_FAILURE = 'DELETE_USER_PROFILE_FAILURE';

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_USER_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_USER_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_USER_IMAGE_FAILURE';